/**
 * ReportExportController
 * Handles PDF and CSV exports for financial reports in the Financial module.
 * Routes: GET /org/reports/financial/:reportType/export?format=pdf|csv&startDate=...&endDate=...
 */

import type { Request, Response } from "express";
import {
  getProfitAndLossStatement,
  getJobProfitability,
  getExpenseByCategory,
  getRevenueByClientFiltered,
  getCustomerAgingReport,
  getCashFlowForecast,
  getVendorSpendReport,
  getMonthlyRevenueTrend,
  getLaborCostReport,
  getClientOutstandingPayments,
  getTechnicianProfitContribution,
  getPaymentCollectionData,
  getClientSpendReport,
  getJobCostBreakdown,
  getInvoiceSummary,
  getMonthlyExpenseTrend,
  getInventoryValuation,
} from "../services/reports.service.js";
import {
  generateFinancialReportPDF,
  buildSummaryCardsHtml,
  buildDataTableHtml,
  buildPLHtml,
} from "../services/pdf.service.js";

// ──────────────────────────────────────────────────────────
// Helpers
// ──────────────────────────────────────────────────────────

const fmt = (n: number, decimals = 2) =>
  `$${n.toLocaleString("en-US", { minimumFractionDigits: decimals, maximumFractionDigits: decimals })}`;

const fmtPct = (n: number) => `${n.toFixed(1)}%`;

function formatDateRange(startDate?: string, endDate?: string): string {
  const opts: Intl.DateTimeFormatOptions = { month: "short", day: "numeric", year: "numeric" };
  const from = startDate ? new Date(startDate).toLocaleDateString("en-US", opts) : "All time";
  const to = endDate ? new Date(endDate).toLocaleDateString("en-US", opts) : "Today";
  return `${from} – ${to}`;
}

function generateCsvFromRows(columns: string[], rows: string[][]): string {
  const escape = (s: string) => (s.includes(",") || s.includes('"') ? `"${s.replace(/"/g, '""')}"` : s);
  const header = columns.map(escape).join(",");
  const body = rows.map((r) => r.map(escape).join(",")).join("\n");
  return `${header}\n${body}`;
}

function streamPdf(res: Response, buffer: Buffer, filename: string) {
  res.setHeader("Content-Type", "application/pdf");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  res.setHeader("Content-Length", buffer.length);
  res.end(buffer);
}

function streamCsv(res: Response, csv: string, filename: string) {
  res.setHeader("Content-Type", "text/csv");
  res.setHeader("Content-Disposition", `attachment; filename="${filename}"`);
  res.end(csv);
}

const REPORT_META: Record<string, { title: string; subtitle: string }> = {
  "profit-loss": {
    title: "Profit & Loss Statement",
    subtitle: "Revenue, cost of goods sold, gross profit, operating expenses, and net income",
  },
  "job-profitability": {
    title: "Job Profitability Report",
    subtitle: "Per-job breakdown of revenue, expenses, profit, and margin",
  },
  "expense-by-category": {
    title: "Expense Breakdown by Category",
    subtitle: "Total spend grouped by expense category with percentage share",
  },
  "revenue-by-client": {
    title: "Revenue by Client",
    subtitle: "Top clients ranked by total invoiced revenue with percentage share",
  },
  "invoice-aging": {
    title: "Invoice Aging Report",
    subtitle: "Outstanding invoices bucketed by age to track overdue risk",
  },
  "cash-flow": {
    title: "Cash Flow Statement",
    subtitle: "Monthly inflows, outflows, and net cash position",
  },
  "vendor-spend": {
    title: "Vendor Spend Summary",
    subtitle: "Total spending per vendor/supplier with job attribution",
  },
  "monthly-revenue-trend": {
    title: "Monthly Revenue Trend",
    subtitle: "Month-over-month revenue, cost, profit, and target comparison",
  },
  "labor-cost": {
    title: "Labor Cost Report",
    subtitle: "Hours worked and total labor cost per employee from timesheet data",
  },
  "client-outstanding": {
    title: "Client Outstanding Payments",
    subtitle: "Clients ranked by outstanding balance with invoice count and age",
  },
  "technician-profit": {
    title: "Technician Profit Contribution",
    subtitle: "Revenue, costs, and profit generated by each technician across their jobs",
  },
  "payment-collection": {
    title: "Payment Collection Rate",
    subtitle: "Monthly invoiced vs collected amounts and AR collection efficiency",
  },
  "client-spend": {
    title: "Client Spend Report",
    subtitle: "Total billed revenue per client with job count and average job value",
  },
  "job-cost-breakdown": {
    title: "Job Cost Breakdown",
    subtitle: "Total costs split across materials, labor, tools, fleet, subcontractors, and overhead",
  },
  "invoice-summary": {
    title: "Invoice Summary",
    subtitle: "Invoice count and dollar totals by status — paid, unpaid, overdue, and draft",
  },
  "monthly-expense-trend": {
    title: "Monthly Expense Trend",
    subtitle: "Month-over-month expense totals by category — identify cost spikes over time",
  },
  "inventory-valuation": {
    title: "Inventory Valuation",
    subtitle: "Total stock value with per-category breakdown of item count and value",
  },
};

// ──────────────────────────────────────────────────────────
// Report builders – return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows }
// ──────────────────────────────────────────────────────────

async function buildProfitLossReport(
  orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  const pl = await getProfitAndLossStatement(orgId, filters);

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Total Revenue", value: fmt(pl.totalRevenue) },
    { label: "Gross Profit", value: fmt(pl.grossProfit), variant: pl.grossProfit >= 0 ? "positive" : "negative" },
    { label: "Net Profit", value: fmt(pl.netProfit), variant: pl.netProfit >= 0 ? "positive" : "negative" },
    {
      label: "Net Margin",
      value: pl.totalRevenue > 0 ? fmtPct((pl.netProfit / pl.totalRevenue) * 100) : "—",
      variant: pl.netProfit >= 0 ? "positive" : "negative",
    },
  ]);

  const mainContentHtml = buildPLHtml(
    [
      {
        header: "Revenue",
        rows: [
          { label: "Total Invoiced Revenue", value: fmt(pl.totalRevenue) },
        ],
        subtotal: { label: "Gross Revenue", value: fmt(pl.totalRevenue), valueClass: "positive" },
      },
      {
        header: "Cost of Goods Sold (COGS)",
        rows: [
          { label: "Materials, Labor & Subcontractors", value: fmt(pl.cogs) },
        ],
        subtotal: { label: "Total COGS", value: fmt(pl.cogs) },
      },
      {
        header: "Gross Profit",
        rows: [
          { label: "Revenue minus COGS", value: fmt(pl.grossProfit) },
        ],
        subtotal: {
          label: "Gross Profit",
          value: fmt(pl.grossProfit),
          valueClass: pl.grossProfit >= 0 ? "positive" : "negative",
        },
      },
      {
        header: "Operating Expenses",
        rows: [
          { label: "Overhead, Admin & Other Operating Costs", value: fmt(pl.operatingExpenses) },
          { label: "Total Job-Linked Expenses", value: fmt(pl.totalJobExpenses) },
        ],
        subtotal: { label: "Total Operating Expenses", value: fmt(pl.totalCost) },
      },
    ],
    {
      label: "Net Profit / (Loss)",
      value: fmt(pl.netProfit),
      valueClass: pl.netProfit >= 0 ? "positive" : "negative",
    }
  );

  const csvColumns = ["Metric", "Amount"];
  const csvRows = [
    ["Total Revenue", fmt(pl.totalRevenue)],
    ["COGS", fmt(pl.cogs)],
    ["Gross Profit", fmt(pl.grossProfit)],
    ["Operating Expenses", fmt(pl.operatingExpenses)],
    ["Total Job Expenses", fmt(pl.totalJobExpenses)],
    ["Total Cost", fmt(pl.totalCost)],
    ["Net Profit", fmt(pl.netProfit)],
    ["Net Margin", pl.totalRevenue > 0 ? fmtPct((pl.netProfit / pl.totalRevenue) * 100) : "0.0%"],
  ];

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildJobProfitabilityReport(
  orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  const rawData = await getJobProfitability(orgId, filters);
  const rows = Array.isArray(rawData) ? rawData : (rawData as any).data ?? [];

  const totalRevenue = rows.reduce((s: number, j: any) => s + j.revenue, 0);
  const totalExpenses = rows.reduce((s: number, j: any) => s + j.totalExpenses, 0);
  const totalProfit = rows.reduce((s: number, j: any) => s + j.profit, 0);

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Jobs", value: String(rows.length) },
    { label: "Total Revenue", value: fmt(totalRevenue) },
    { label: "Total Expenses", value: fmt(totalExpenses) },
    { label: "Total Profit", value: fmt(totalProfit), variant: totalProfit >= 0 ? "positive" : "negative" },
  ]);

  const tableRows = rows.map((j: any) => {
    const _profitVariant = j.profit >= 0 ? "positive" : "negative";
    return [
      j.jobNumber ?? "—",
      j.jobName ?? "—",
      j.clientName ?? "—",
      { text: fmt(j.revenue), align: "right" },
      { text: fmt(j.totalExpenses), align: "right" },
      { text: fmt(j.profit), align: "right" },
      {
        text: fmtPct(j.profitMargin),
        badge: j.profit >= 0 ? "On Track" : "Over Budget",
        badgeVariant: j.profit >= 0 ? "green" : "red",
      },
    ] as any[];
  });

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Job-Level Profitability",
    columns: [
      { label: "Job #" },
      { label: "Job Name" },
      { label: "Client" },
      { label: "Revenue", align: "right" },
      { label: "Expenses", align: "right" },
      { label: "Profit", align: "right" },
      { label: "Margin" },
    ],
    rows: tableRows,
    totalsRow: [
      "",
      "TOTALS",
      "",
      fmt(totalRevenue),
      fmt(totalExpenses),
      fmt(totalProfit),
      totalRevenue > 0 ? fmtPct((totalProfit / totalRevenue) * 100) : "—",
    ],
  });

  const csvColumns = ["Job #", "Job Name", "Client", "Revenue", "Expenses", "Profit", "Margin %"];
  const csvRows = rows.map((j: any) => [
    j.jobNumber ?? "",
    j.jobName ?? "",
    j.clientName ?? "",
    fmt(j.revenue),
    fmt(j.totalExpenses),
    fmt(j.profit),
    fmtPct(j.profitMargin),
  ]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildExpenseByCategoryReport(
  orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  const data = await getExpenseByCategory(orgId, filters);
  const total = data.reduce((s, d) => s + d.amount, 0);

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Categories", value: String(data.length) },
    { label: "Total Expenses", value: fmt(total) },
    { label: "Largest Category", value: data[0]?.category ?? "—" },
    { label: "Largest Amount", value: data[0] ? fmt(data[0].amount) : "—" },
  ]);

  const tableRows = data.map((d) => [
    d.category,
    { text: fmt(d.amount), align: "right" },
    { text: total > 0 ? fmtPct((d.amount / total) * 100) : "0.0%", align: "right" },
  ] as any[]);

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Expenses by Category",
    columns: [
      { label: "Category" },
      { label: "Amount", align: "right" },
      { label: "% of Total", align: "right" },
    ],
    rows: tableRows,
    totalsRow: ["TOTAL", fmt(total), "100.0%"],
  });

  const csvColumns = ["Category", "Amount", "% of Total"];
  const csvRows = data.map((d) => [
    d.category,
    fmt(d.amount),
    total > 0 ? fmtPct((d.amount / total) * 100) : "0.0%",
  ]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildRevenueByClientReport(
  orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  const data = await getRevenueByClientFiltered(orgId, filters);
  const total = data.reduce((s, d) => s + d.revenue, 0);

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Clients", value: String(data.length) },
    { label: "Total Revenue", value: fmt(total) },
    { label: "Top Client", value: data[0]?.client ?? "—" },
    { label: "Top Client Revenue", value: data[0] ? fmt(data[0].revenue) : "—" },
  ]);

  const tableRows = data.map((d, i) => [
    String(i + 1),
    d.client,
    { text: fmt(d.revenue), align: "right" },
    { text: fmtPct(d.percentage), align: "right" },
  ] as any[]);

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Revenue by Client",
    columns: [
      { label: "#", align: "center" },
      { label: "Client" },
      { label: "Total Revenue", align: "right" },
      { label: "% of Total", align: "right" },
    ],
    rows: tableRows,
    totalsRow: ["", "TOTAL", fmt(total), "100.0%"],
  });

  const csvColumns = ["Rank", "Client", "Revenue", "% of Total"];
  const csvRows = data.map((d, i) => [String(i + 1), d.client, fmt(d.revenue), fmtPct(d.percentage)]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildInvoiceAgingReport(
  orgId: string | undefined,
  _filters: { startDate?: string; endDate?: string }
) {
  const agingMap = await getCustomerAgingReport(orgId, {});
  const data: any[] = Array.isArray(agingMap) ? agingMap : Object.values(agingMap);

  const totals = { "0-30": 0, "31-60": 0, "61-90": 0, "90+": 0, total: 0 };
  data.forEach((d: any) => {
    totals["0-30"] += d["0-30"] ?? 0;
    totals["31-60"] += d["31-60"] ?? 0;
    totals["61-90"] += d["61-90"] ?? 0;
    totals["90+"] += d["90+"] ?? 0;
    totals.total += d.total ?? 0;
  });

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Clients w/ Outstanding", value: String(data.length) },
    { label: "Total Outstanding", value: fmt(totals.total), variant: "negative" },
    { label: "Current (0–30 days)", value: fmt(totals["0-30"]) },
    { label: "Overdue (90+ days)", value: fmt(totals["90+"]), variant: totals["90+"] > 0 ? "negative" : "neutral" },
  ]);

  const tableRows = data.map((d: any) => [
    d.client ?? "—",
    { text: fmt(d["0-30"] ?? 0), align: "right" },
    { text: fmt(d["31-60"] ?? 0), align: "right" },
    { text: fmt(d["61-90"] ?? 0), align: "right" },
    { text: fmt(d["90+"] ?? 0), align: "right" },
    { text: fmt(d.total ?? 0), align: "right" },
  ] as any[]);

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Invoice Aging by Client",
    columns: [
      { label: "Client" },
      { label: "0–30 Days", align: "right" },
      { label: "31–60 Days", align: "right" },
      { label: "61–90 Days", align: "right" },
      { label: "90+ Days", align: "right" },
      { label: "Total", align: "right" },
    ],
    rows: tableRows,
    totalsRow: [
      "TOTAL",
      fmt(totals["0-30"]),
      fmt(totals["31-60"]),
      fmt(totals["61-90"]),
      fmt(totals["90+"]),
      fmt(totals.total),
    ],
  });

  const csvColumns = ["Client", "0-30 Days", "31-60 Days", "61-90 Days", "90+ Days", "Total"];
  const csvRows = data.map((d: any) => [
    d.client ?? "",
    fmt(d["0-30"] ?? 0),
    fmt(d["31-60"] ?? 0),
    fmt(d["61-90"] ?? 0),
    fmt(d["90+"] ?? 0),
    fmt(d.total ?? 0),
  ]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildCashFlowReport(
  orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  // getCashFlowForecast returns: Array<{ month, inflows, outflows, projected, actual }>
  const monthly = await getCashFlowForecast(orgId, filters);

  const totalInflows = monthly.reduce((s, m) => s + (m.inflows ?? 0), 0);
  const totalOutflows = monthly.reduce((s, m) => s + (m.outflows ?? 0), 0);
  const netCash = totalInflows - totalOutflows;

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Total Inflows", value: fmt(totalInflows), variant: "positive" },
    { label: "Total Outflows", value: fmt(totalOutflows) },
    { label: "Net Cash", value: fmt(netCash), variant: netCash >= 0 ? "positive" : "negative" },
    { label: "Periods", value: String(monthly.length) },
  ]);

  const tableRows = monthly.map((m) => {
    const inflow = m.inflows ?? 0;
    const outflow = m.outflows ?? 0;
    const net = inflow - outflow;
    return [
      m.month ?? "—",
      { text: fmt(inflow), align: "right" },
      { text: fmt(outflow), align: "right" },
      { text: fmt(net), align: "right" },
    ] as any[];
  });

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Monthly Cash Flow",
    columns: [
      { label: "Month" },
      { label: "Inflows (Invoiced)", align: "right" },
      { label: "Outflows (Expenses)", align: "right" },
      { label: "Net Cash", align: "right" },
    ],
    rows: tableRows,
    totalsRow: ["TOTAL", fmt(totalInflows), fmt(totalOutflows), fmt(netCash)],
  });

  const csvColumns = ["Month", "Inflows", "Outflows", "Net Cash"];
  const csvRows = monthly.map((m) => [m.month ?? "", fmt(m.inflows ?? 0), fmt(m.outflows ?? 0), fmt((m.inflows ?? 0) - (m.outflows ?? 0))]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildVendorSpendReport(
  orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  // getVendorSpendReport returns: Array<{ vendor, totalSpend, unpaid, invoices }>
  const data = await getVendorSpendReport(orgId, filters);
  const total = data.reduce((s, v) => s + v.totalSpend, 0);

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Vendors", value: String(data.length) },
    { label: "Total Spend", value: fmt(total) },
    { label: "Top Vendor", value: data[0]?.vendor ?? "—" },
    { label: "Top Spend", value: data[0] ? fmt(data[0].totalSpend) : "—" },
  ]);

  const tableRows = data.map((v, i) => [
    String(i + 1),
    v.vendor ?? "—",
    { text: fmt(v.totalSpend), align: "right" },
    { text: total > 0 ? fmtPct((v.totalSpend / total) * 100) : "0.0%", align: "right" },
  ] as any[]);

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Vendor Spend Breakdown",
    columns: [
      { label: "#", align: "center" },
      { label: "Vendor" },
      { label: "Total Spend", align: "right" },
      { label: "% of Total", align: "right" },
    ],
    rows: tableRows,
    totalsRow: ["", "TOTAL", fmt(total), "100.0%"],
  });

  const csvColumns = ["Rank", "Vendor", "Total Spend", "% of Total"];
  const csvRows = data.map((v, i) => [
    String(i + 1),
    v.vendor ?? "",
    fmt(v.totalSpend),
    total > 0 ? fmtPct((v.totalSpend / total) * 100) : "0.0%",
  ]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildMonthlyRevenueTrendReport(
  _orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  // getMonthlyRevenueTrend does not filter by org; pass date filters
  const data = await getMonthlyRevenueTrend(filters);

  const totalRevenue = data.reduce((s, m) => s + m.revenue, 0);
  const totalCost = data.reduce((s, m) => s + m.cost, 0);
  const totalProfit = data.reduce((s, m) => s + m.profit, 0);

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Months", value: String(data.length) },
    { label: "Total Revenue", value: fmt(totalRevenue), variant: "positive" },
    { label: "Total Cost", value: fmt(totalCost) },
    { label: "Total Profit", value: fmt(totalProfit), variant: totalProfit >= 0 ? "positive" : "negative" },
  ]);

  const hasTargets = data.some((m) => m.target != null);
  const columns: Array<{ label: string; align?: "left" | "right" | "center" }> = [
    { label: "Month" },
    { label: "Revenue", align: "right" },
    { label: "Cost", align: "right" },
    { label: "Profit", align: "right" },
    ...(hasTargets ? [{ label: "Target", align: "right" as const }] : []),
    ...(hasTargets ? [{ label: "vs Target", align: "right" as const }] : []),
  ];

  const tableRows = data.map((m) => {
    const row: any[] = [
      m.month,
      { text: fmt(m.revenue), align: "right" },
      { text: fmt(m.cost), align: "right" },
      { text: fmt(m.profit), align: "right" },
    ];
    if (hasTargets) {
      const target = m.target ?? 0;
      const diff = m.revenue - target;
      row.push({ text: target > 0 ? fmt(target) : "—", align: "right" });
      row.push({ text: target > 0 ? `${diff >= 0 ? "+" : ""}${fmt(diff)}` : "—", align: "right" });
    }
    return row;
  });

  const totalsRow: string[] = ["TOTAL", fmt(totalRevenue), fmt(totalCost), fmt(totalProfit)];
  if (hasTargets) totalsRow.push("—", "—");

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Monthly Revenue vs Cost vs Profit",
    columns,
    rows: tableRows,
    totalsRow,
  });

  const csvColumns = ["Month", "Revenue", "Cost", "Profit", ...(hasTargets ? ["Target", "vs Target"] : [])];
  const csvRows = data.map((m) => {
    const row = [m.month, fmt(m.revenue), fmt(m.cost), fmt(m.profit)];
    if (hasTargets) {
      const target = m.target ?? 0;
      const diff = m.revenue - target;
      row.push(target > 0 ? fmt(target) : "—", target > 0 ? `${diff >= 0 ? "+" : ""}${fmt(diff)}` : "—");
    }
    return row;
  });

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildLaborCostReport(
  orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  const data = await getLaborCostReport(orgId, filters);

  const totalHours = data.reduce((s, l) => s + l.hoursWorked, 0);
  const totalCost = data.reduce((s, l) => s + l.laborCost, 0);

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Employees", value: String(data.length) },
    { label: "Total Hours", value: totalHours.toFixed(1) + " hrs" },
    { label: "Total Labor Cost", value: fmt(totalCost) },
    { label: "Avg Hourly Rate", value: data.length > 0 ? fmt(totalCost / Math.max(totalHours, 1)) : "—" },
  ]);

  const tableRows = data.map((l) => [
    l.technician ?? "—",
    { text: `$${l.hourlyRate.toFixed(2)}/hr`, align: "right" },
    { text: l.hoursWorked.toFixed(1), align: "right" },
    { text: fmt(l.laborCost), align: "right" },
    { text: String(l.jobs), align: "center" },
  ] as any[]);

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Labor Cost by Employee",
    columns: [
      { label: "Employee" },
      { label: "Hourly Rate", align: "right" },
      { label: "Hours Worked", align: "right" },
      { label: "Total Cost", align: "right" },
      { label: "Entries", align: "center" },
    ],
    rows: tableRows,
    totalsRow: ["TOTAL", "—", totalHours.toFixed(1), fmt(totalCost), "—"],
  });

  const csvColumns = ["Employee", "Hourly Rate", "Hours Worked", "Total Labor Cost", "Entries"];
  const csvRows = data.map((l) => [
    l.technician ?? "",
    `$${l.hourlyRate.toFixed(2)}`,
    l.hoursWorked.toFixed(1),
    fmt(l.laborCost),
    String(l.jobs),
  ]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildClientOutstandingReport(
  orgId: string | undefined,
  _filters: { startDate?: string; endDate?: string }
) {
  const data = await getClientOutstandingPayments(orgId, {});

  const totalOutstanding = data.reduce((s, c) => s + c.outstanding, 0);
  const totalInvoices = data.reduce((s, c) => s + c.invoices, 0);

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Clients with Balance", value: String(data.length) },
    { label: "Total Outstanding", value: fmt(totalOutstanding), variant: "negative" },
    { label: "Open Invoices", value: String(totalInvoices) },
    { label: "Largest Balance", value: data[0] ? fmt(data[0].outstanding) : "—", variant: data.length > 0 ? "negative" : "neutral" },
  ]);

  const tableRows = data.map((c, i) => [
    String(i + 1),
    c.client,
    { text: fmt(c.outstanding), align: "right" },
    { text: String(c.invoices), align: "center" },
    c.oldestDue,
  ] as any[]);

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Outstanding Balances by Client",
    columns: [
      { label: "#", align: "center" },
      { label: "Client" },
      { label: "Outstanding", align: "right" },
      { label: "Open Invoices", align: "center" },
      { label: "Oldest Due" },
    ],
    rows: tableRows,
    totalsRow: ["", "TOTAL", fmt(totalOutstanding), String(totalInvoices), ""],
  });

  const csvColumns = ["Rank", "Client", "Outstanding", "Open Invoices", "Oldest Due"];
  const csvRows = data.map((c, i) => [
    String(i + 1),
    c.client,
    fmt(c.outstanding),
    String(c.invoices),
    c.oldestDue,
  ]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildTechnicianProfitReport(
  orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  const data = await getTechnicianProfitContribution(orgId, filters);

  const totalRevenue = data.reduce((s, t) => s + t.revenue, 0);
  const totalCost = data.reduce((s, t) => s + t.cost, 0);
  const totalProfit = data.reduce((s, t) => s + t.profit, 0);

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Technicians", value: String(data.length) },
    { label: "Total Revenue", value: fmt(totalRevenue) },
    { label: "Total Profit", value: fmt(totalProfit), variant: totalProfit >= 0 ? "positive" : "negative" },
    {
      label: "Avg Margin",
      value: totalRevenue > 0 ? fmtPct((totalProfit / totalRevenue) * 100) : "—",
      variant: totalProfit >= 0 ? "positive" : "negative",
    },
  ]);

  const tableRows = data.map((t) => [
    t.name ?? "—",
    { text: fmt(t.revenue), align: "right" },
    { text: fmt(t.cost), align: "right" },
    { text: fmt(t.profit), align: "right" },
    { text: fmtPct(t.margin), align: "right" },
  ] as any[]);

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Profit Contribution by Technician",
    columns: [
      { label: "Technician" },
      { label: "Revenue", align: "right" },
      { label: "Cost", align: "right" },
      { label: "Profit", align: "right" },
      { label: "Margin %", align: "right" },
    ],
    rows: tableRows,
    totalsRow: [
      "TOTAL",
      fmt(totalRevenue),
      fmt(totalCost),
      fmt(totalProfit),
      totalRevenue > 0 ? fmtPct((totalProfit / totalRevenue) * 100) : "—",
    ],
  });

  const csvColumns = ["Technician", "Revenue", "Cost", "Profit", "Margin %"];
  const csvRows = data.map((t) => [
    t.name ?? "",
    fmt(t.revenue),
    fmt(t.cost),
    fmt(t.profit),
    fmtPct(t.margin),
  ]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildPaymentCollectionReport(
  orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  const data = await getPaymentCollectionData(orgId, filters);

  const totalExpected = data.reduce((s, m) => s + m.expected, 0);
  const totalCollected = data.reduce((s, m) => s + m.collected, 0);
  const overallRate = totalExpected > 0 ? (totalCollected / totalExpected) * 100 : 0;

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Months", value: String(data.length) },
    { label: "Total Invoiced", value: fmt(totalExpected) },
    { label: "Total Collected", value: fmt(totalCollected), variant: "positive" },
    {
      label: "Overall Rate",
      value: fmtPct(overallRate),
      variant: overallRate >= 80 ? "positive" : overallRate >= 50 ? "neutral" : "negative",
    },
  ]);

  const tableRows = data.map((m) => [
    m.month,
    { text: fmt(m.expected), align: "right" },
    { text: fmt(m.collected), align: "right" },
    { text: fmt(m.expected - m.collected), align: "right" },
    { text: fmtPct(m.collectionRate), align: "right" },
  ] as any[]);

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Monthly Payment Collection",
    columns: [
      { label: "Month" },
      { label: "Invoiced", align: "right" },
      { label: "Collected", align: "right" },
      { label: "Outstanding", align: "right" },
      { label: "Rate %", align: "right" },
    ],
    rows: tableRows,
    totalsRow: [
      "TOTAL",
      fmt(totalExpected),
      fmt(totalCollected),
      fmt(totalExpected - totalCollected),
      fmtPct(overallRate),
    ],
  });

  const csvColumns = ["Month", "Invoiced", "Collected", "Outstanding", "Collection Rate %"];
  const csvRows = data.map((m) => [
    m.month,
    fmt(m.expected),
    fmt(m.collected),
    fmt(m.expected - m.collected),
    fmtPct(m.collectionRate),
  ]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildClientSpendReport(
  orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  const data = await getClientSpendReport(orgId, filters);
  const totalRevenue = data.reduce((s, c) => s + c.revenue, 0);
  const totalJobs = data.reduce((s, c) => s + c.jobs, 0);

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Clients", value: String(data.length) },
    { label: "Total Billed", value: fmt(totalRevenue) },
    { label: "Total Jobs", value: String(totalJobs) },
    { label: "Top Client", value: data[0]?.client ?? "—" },
  ]);

  const tableRows = data.map((c, i) => [
    String(i + 1),
    c.client,
    { text: fmt(c.revenue), align: "right" },
    { text: String(c.jobs), align: "center" },
    { text: fmt(c.avgJobValue), align: "right" },
  ] as any[]);

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Client Spend Summary",
    columns: [
      { label: "#", align: "center" },
      { label: "Client" },
      { label: "Total Billed", align: "right" },
      { label: "Jobs", align: "center" },
      { label: "Avg Job Value", align: "right" },
    ],
    rows: tableRows,
    totalsRow: ["", "TOTAL", fmt(totalRevenue), String(totalJobs), "—"],
  });

  const csvColumns = ["Rank", "Client", "Total Billed", "Jobs", "Avg Job Value"];
  const csvRows = data.map((c, i) => [
    String(i + 1), c.client, fmt(c.revenue), String(c.jobs), fmt(c.avgJobValue),
  ]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildJobCostBreakdownReport(
  orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  // Returns { materials, labor, tools, fleet, subcontractor, overhead }
  const breakdown = await getJobCostBreakdown(orgId, filters);
  const categories = [
    { label: "Materials", value: breakdown.materials },
    { label: "Labor", value: breakdown.labor },
    { label: "Tools", value: breakdown.tools },
    { label: "Fleet / Vehicle", value: breakdown.fleet },
    { label: "Subcontractor", value: breakdown.subcontractor },
    { label: "Overhead / Other", value: breakdown.overhead },
  ].filter((c) => c.value > 0);

  const total = Object.values(breakdown).reduce((s, v) => s + v, 0);

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Total Job Cost", value: fmt(total) },
    { label: "Materials", value: fmt(breakdown.materials) },
    { label: "Labor", value: fmt(breakdown.labor) },
    { label: "Subcontractor", value: fmt(breakdown.subcontractor) },
  ]);

  const tableRows = categories.map((c) => [
    c.label,
    { text: fmt(c.value), align: "right" },
    { text: total > 0 ? fmtPct((c.value / total) * 100) : "0.0%", align: "right" },
  ] as any[]);

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Cost Breakdown by Category",
    columns: [
      { label: "Category" },
      { label: "Amount", align: "right" },
      { label: "% of Total", align: "right" },
    ],
    rows: tableRows,
    totalsRow: ["TOTAL", fmt(total), "100.0%"],
  });

  const csvColumns = ["Category", "Amount", "% of Total"];
  const csvRows = categories.map((c) => [
    c.label, fmt(c.value), total > 0 ? fmtPct((c.value / total) * 100) : "0.0%",
  ]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildInvoiceSummaryReport(
  orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  const data = await getInvoiceSummary(orgId, filters);
  const collectionRate = data.totalRevenue > 0
    ? (data.collected / data.totalRevenue) * 100
    : 0;

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Total Invoices", value: String(data.totalIssued) },
    { label: "Total Billed", value: fmt(data.totalRevenue) },
    { label: "Collected", value: fmt(data.collected), variant: "positive" },
    {
      label: "Collection Rate",
      value: fmtPct(collectionRate),
      variant: collectionRate >= 80 ? "positive" : collectionRate >= 50 ? "neutral" : "negative",
    },
  ]);

  const statusRows = [
    ["Paid", String(data.paid), fmt(data.collected), { text: "Paid", badge: "Paid", badgeVariant: "green" }],
    ["Unpaid / Sent", String(data.unpaid), "—", { text: "Open", badge: "Open", badgeVariant: "blue" }],
    ["Overdue", String(data.overdue), fmt(data.outstanding), { text: "Overdue", badge: "Overdue", badgeVariant: "red" }],
  ] as any[][];

  const statusTable = buildDataTableHtml({
    sectionTitle: "Invoice Status Breakdown",
    columns: [
      { label: "Status" },
      { label: "Count", align: "center" },
      { label: "Amount", align: "right" },
      { label: "" },
    ],
    rows: statusRows,
    totalsRow: ["TOTAL", String(data.totalIssued), fmt(data.totalRevenue), ""],
  });

  const summaryRows = [
    ["Total Billed", fmt(data.totalRevenue)],
    ["Amount Collected", fmt(data.collected)],
    ["Amount Outstanding", fmt(data.outstanding)],
    ["Collection Rate", fmtPct(collectionRate)],
  ] as any[][];

  const summaryTable = buildDataTableHtml({
    sectionTitle: "Financial Summary",
    columns: [{ label: "Metric" }, { label: "Value", align: "right" }],
    rows: summaryRows,
  });

  const mainContentHtml = statusTable + summaryTable;

  const csvColumns = ["Metric", "Count", "Amount"];
  const csvRows = [
    ["Total Invoices", String(data.totalIssued), fmt(data.totalRevenue)],
    ["Paid", String(data.paid), fmt(data.collected)],
    ["Unpaid / Sent", String(data.unpaid), "—"],
    ["Overdue", String(data.overdue), fmt(data.outstanding)],
    ["Collection Rate", "—", fmtPct(collectionRate)],
  ];

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildMonthlyExpenseTrendReport(
  orgId: string | undefined,
  filters: { startDate?: string; endDate?: string }
) {
  // Returns Array<{ month, [categoryKey]: number, ... }>
  const raw = await getMonthlyExpenseTrend(orgId, filters);

  // Collect all category keys across all months
  const categoryKeys = Array.from(
    new Set(raw.flatMap((m) => Object.keys(m).filter((k) => k !== "month")))
  );

  const categoryLabels: Record<string, string> = {
    materials: "Materials", equipment: "Equipment", transportation: "Transportation",
    permits: "Permits", subcontractor: "Subcontractor", utilities: "Utilities",
    tools: "Tools", safety: "Safety", fleet: "Fleet", maintenance: "Maintenance",
    fuel: "Fuel", tires: "Tires", registration: "Registration", repairs: "Repairs",
    insurance: "Insurance", office_supplies: "Office Supplies", rent: "Rent",
    internet: "Internet", job_labor: "Job Labor", other: "Other",
  };

  // Grand totals per category
  const categoryTotals: Record<string, number> = {};
  raw.forEach((m) => {
    categoryKeys.forEach((k) => {
      categoryTotals[k] = (categoryTotals[k] ?? 0) + (m[k] ?? 0);
    });
  });

  const grandTotal = Object.values(categoryTotals).reduce((s, v) => s + v, 0);
  const monthlyTotals = raw.map((m) =>
    categoryKeys.reduce((s, k) => s + (m[k] ?? 0), 0)
  );
  const totalAllMonths = monthlyTotals.reduce((s, v) => s + v, 0);

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Months", value: String(raw.length) },
    { label: "Total Expenses", value: fmt(totalAllMonths) },
    { label: "Categories", value: String(categoryKeys.length) },
    {
      label: "Avg Monthly",
      value: raw.length > 0 ? fmt(totalAllMonths / raw.length) : "—",
    },
  ]);

  // Table: Month | Total | Top-3 categories
  const topCats = categoryKeys
    .slice()
    .sort((a, b) => (categoryTotals[b] ?? 0) - (categoryTotals[a] ?? 0))
    .slice(0, 3);

  const columns = [
    { label: "Month" },
    ...topCats.map((k) => ({ label: categoryLabels[k] ?? k, align: "right" as const })),
    { label: "Other", align: "right" as const },
    { label: "Month Total", align: "right" as const },
  ];

  const tableRows = raw.map((m, i) => {
    const topVals = topCats.map((k) => ({ text: fmt(m[k] ?? 0), align: "right" }));
    const otherVal = categoryKeys
      .filter((k) => !topCats.includes(k))
      .reduce((s, k) => s + (m[k] ?? 0), 0);
    return [m.month, ...topVals, { text: fmt(otherVal), align: "right" }, { text: fmt(monthlyTotals[i] ?? 0), align: "right" }] as any[];
  });

  const topTotals = topCats.map((k) => fmt(categoryTotals[k] ?? 0));
  const otherTotal = categoryKeys.filter((k) => !topCats.includes(k)).reduce((s, k) => s + (categoryTotals[k] ?? 0), 0);
  const totalsRow = ["TOTAL", ...topTotals, fmt(otherTotal), fmt(grandTotal)];

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Monthly Expense Trend by Category",
    columns,
    rows: tableRows,
    totalsRow,
  });

  const csvColumns = ["Month", ...categoryKeys.map((k) => categoryLabels[k] ?? k), "Month Total"];
  const csvRows = raw.map((m, i) => [
    m.month,
    ...categoryKeys.map((k) => fmt(m[k] ?? 0)),
    fmt(monthlyTotals[i] ?? 0),
  ]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

async function buildInventoryValuationReport(
  orgId: string | undefined,
  _filters: { startDate?: string; endDate?: string }
) {
  // Returns { totalValue, itemCount, categories: [{category, value, items}] }
  const data = await getInventoryValuation(orgId, {});
  const { totalValue, itemCount, categories } = data;

  const summaryCardsHtml = buildSummaryCardsHtml([
    { label: "Total Stock Value", value: fmt(totalValue) },
    { label: "Total SKUs", value: String(itemCount) },
    { label: "Categories", value: String(categories.length) },
    { label: "Top Category", value: categories[0]?.category ?? "—" },
  ]);

  const sortedCats = [...categories].sort((a, b) => b.value - a.value);

  const tableRows = sortedCats.map((c, i) => [
    String(i + 1),
    c.category,
    { text: String(c.items), align: "center" },
    { text: fmt(c.value), align: "right" },
    { text: totalValue > 0 ? fmtPct((c.value / totalValue) * 100) : "0.0%", align: "right" },
  ] as any[]);

  const mainContentHtml = buildDataTableHtml({
    sectionTitle: "Stock Valuation by Category",
    columns: [
      { label: "#", align: "center" },
      { label: "Category" },
      { label: "SKUs", align: "center" },
      { label: "Total Value", align: "right" },
      { label: "% of Total", align: "right" },
    ],
    rows: tableRows,
    totalsRow: ["", "TOTAL", String(itemCount), fmt(totalValue), "100.0%"],
  });

  const csvColumns = ["Rank", "Category", "SKUs", "Total Value", "% of Total"];
  const csvRows = sortedCats.map((c, i) => [
    String(i + 1),
    c.category,
    String(c.items),
    fmt(c.value),
    totalValue > 0 ? fmtPct((c.value / totalValue) * 100) : "0.0%",
  ]);

  return { summaryCardsHtml, mainContentHtml, csvColumns, csvRows };
}

// ──────────────────────────────────────────────────────────
// Main export handler
// GET /org/reports/financial/:reportType/export
// ──────────────────────────────────────────────────────────

export const exportFinancialReportHandler = async (req: Request, res: Response) => {
  try {
    const reportType = req.params.reportType as string;
    const format = (req.query.format as string) || "pdf";
    const organizationId = req.query.organizationId as string | undefined;
    const startDate = req.query.startDate as string | undefined;
    const endDate = req.query.endDate as string | undefined;
    const filters: { startDate?: string; endDate?: string } = {
      ...(startDate !== undefined && { startDate }),
      ...(endDate !== undefined && { endDate }),
    };

    const meta = REPORT_META[reportType];
    if (!meta) {
      return res.status(404).json({ success: false, error: `Unknown report type: ${reportType}` });
    }

    // Build report data
    let report: { summaryCardsHtml: string; mainContentHtml: string; csvColumns: string[]; csvRows: string[][] };

    switch (reportType) {
      case "profit-loss":
        report = await buildProfitLossReport(organizationId, filters);
        break;
      case "job-profitability":
        report = await buildJobProfitabilityReport(organizationId, filters);
        break;
      case "expense-by-category":
        report = await buildExpenseByCategoryReport(organizationId, filters);
        break;
      case "revenue-by-client":
        report = await buildRevenueByClientReport(organizationId, filters);
        break;
      case "invoice-aging":
        report = await buildInvoiceAgingReport(organizationId, filters);
        break;
      case "cash-flow":
        report = await buildCashFlowReport(organizationId, filters);
        break;
      case "vendor-spend":
        report = await buildVendorSpendReport(organizationId, filters);
        break;
      case "monthly-revenue-trend":
        report = await buildMonthlyRevenueTrendReport(organizationId, filters);
        break;
      case "labor-cost":
        report = await buildLaborCostReport(organizationId, filters);
        break;
      case "client-outstanding":
        report = await buildClientOutstandingReport(organizationId, filters);
        break;
      case "technician-profit":
        report = await buildTechnicianProfitReport(organizationId, filters);
        break;
      case "payment-collection":
        report = await buildPaymentCollectionReport(organizationId, filters);
        break;
      case "client-spend":
        report = await buildClientSpendReport(organizationId, filters);
        break;
      case "job-cost-breakdown":
        report = await buildJobCostBreakdownReport(organizationId, filters);
        break;
      case "invoice-summary":
        report = await buildInvoiceSummaryReport(organizationId, filters);
        break;
      case "monthly-expense-trend":
        report = await buildMonthlyExpenseTrendReport(organizationId, filters);
        break;
      case "inventory-valuation":
        report = await buildInventoryValuationReport(organizationId, filters);
        break;
      default:
        return res.status(404).json({ success: false, error: `Unknown report type: ${reportType}` });
    }

    const dateRange = formatDateRange(startDate, endDate);
    const generatedDate = new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });
    const safeReportId = reportType.toUpperCase().replace(/-/g, "_");

    if (format === "csv") {
      const csv = generateCsvFromRows(report.csvColumns, report.csvRows);
      const filename = `t3-${reportType}-${new Date().toISOString().slice(0, 10)}.csv`;
      return streamCsv(res, csv, filename);
    }

    // Default: PDF
    const pdfBuffer = await generateFinancialReportPDF({
      reportTitle: meta.title,
      reportSubtitle: meta.subtitle,
      reportId: safeReportId,
      dateRange,
      organizationName: "T3 Mechanical Inc.",
      generatedDate,
      summaryCardsHtml: report.summaryCardsHtml,
      mainContentHtml: report.mainContentHtml,
    });

    const filename = `t3-${reportType}-${new Date().toISOString().slice(0, 10)}.pdf`;
    return streamPdf(res, pdfBuffer, filename);
  } catch (err) {
    console.error("[ReportExportController]", err);
    return res.status(500).json({
      success: false,
      error: err instanceof Error ? err.message : "Failed to generate report",
    });
  }
};
